mybatis:
  type-aliases-package: TravelGuide.entity
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travelguides
    username: root
    password:
    